apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{IMAGE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  selector:
    matchLabels:
      app: {{IMAGE_NAME}}
  endpoints:
    - port: metrics
      path: /actuator/prometheus