#Replace this file with your "service_v1.0.openapi.yaml" file
openapi: 3.0.1
info:
  title: Some service
  description: This is a sample API of some service
  contact:
    email: email.email@t-systems.com
  x-logo:
    url: 'static/img/img_fs-logo.png'
    altText: Fieldservice Digital Hub
  version: 1.0.0
servers:
  - url: 'https://service.de/v1'
  - url: 'http://service.service.de/v1'
tags:
  - name: service
    description: Everything about service
paths:
  /service/{id}:
    get:
      tags:
        - tag
      summary: Operation summary
      operationId: operationId
      parameters:
        - name: id
          in: path
          description: The id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: successful operation
      x-codegen-request-body-name: body
components:
  schemas:
    schema:
      required:
        - id
      type: object
      properties:
        id:
          type: integer
          format: int64
    Problem:
      title: Problem Details Object
      description: |
        The problem details object is described as a part of [RFC7807](https://tools.ietf.org/html/rfc7807).
        It defines finer-grained definition of the problem normally returned within HTTP response codes: 3xx, 4xx, 5xx.
        See [RFC7807-page-5)](https://tools.ietf.org/html/rfc7807#page-5) for more details.
      type: object
      properties:
        type:
          type: string
          description: |
            A URI reference [RFC3986](https://tools.ietf.org/html/rfc7807) that identifies the problem type. Consumers MUST use the `type` string as the primary identifier for the problem type.
          format: uri
          default: 'about:blank'
          example: '/problem/invalid-param'
        title:
          type: string
          description: |
            A short, human-readable summary of the problem type. Consumers SHOULD NOT automatically dereference the type URI.
        status:
          type: integer
          description: |
            The HTTP status code [RFC7231-section-6](https://tools.ietf.org/html/rfc7231#section-6) generated by the origin server for this occurrence of the problem. The `status` member, if present, is only advisory; it conveys the HTTP status code used for the convenience of the consumer. Generators MUST use the same status code in the actual HTTP response.
        detail:
          type: string
          description: |
            A human-readable explanation specific to this occurrence of the problem. The `detail` member, if present, ought to focus on helping the client correct the problem, rather than giving debugging information.
        instance:
          type: string
          description: |
            A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
          format: uri
      required:
        - title
        - type
      example:
        type: '/problem/invalid-param'
        title: Mandatory parameters are missing or contain invalid values.
      x-examples:
        Problem Example Numeric Error Code:
          type: '/problem/00000001'
          title: Mandatory parameters are missing or contain invalid values.
        Problem Example Alphabetic Error Code:
          type: '/problem/invalid-param'
          title: Mandatory parameters are missing or contain invalid values.